import { Inter, Space_Grotesk } from "next/font/google";
// import { createFlagsmithInstance } from "flagsmith/isomorphic";

import "./globals.css";
// import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

const space_grotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
//   const flagsmith = createFlagsmithInstance();
//   await flagsmith.init({
//     environmentID: process.env.NEXT_PUBLIC_FLAGSMITH_ENVIRONMENT_ID,
//   });
//   const serverState = flagsmith.getState();
//   console.log(serverState);

  return (
    <html lang="en">
      {/* <Providers serverState={serverState}> */}
        <body className={space_grotesk.className}>{children}</body>
      {/* </Providers> */}
    </html>
  );
}
